# Generated by Django 5.2.3 on 2025-06-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование ресторна/кафе/магазина', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='from_where',
            field=models.CharField(help_text='Откуда блюда', max_length=20),
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaraunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.restaraunt', verbose_name='Рестораны/кафе/магащины'),
        ),
    ]
