# Generated by Django 5.2.3 on 2025-06-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_restaraunt_alter_category_name_alter_dishes_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='from_where',
        ),
    ]
